"""
Django settings for virtual_library project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import ugettext_lazy as ugettext

# Build paths inside the project like this: os.path.join(BASE_DIR_PATH, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR_PATH = Path(os.path.abspath(__file__)).parents[2]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

class Settings:

    # Application definition

    INSTALLED_APPS = [
        'alexecx_django.apps.AlexecxDjangoConfig',
        'widget_tweaks',
    ]

    # Password validation
    # https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

    AUTHENTICATION_BACKENDS = [
        # Custom backend for login using email
        'alexecx_django.auth.AuthenticationEmailBackend', 
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/2.0/topics/i18n/

    #Emplacement des traductions

    LOCALE_PATHS = (
        os.path.join(BASE_DIR_PATH, 'alexecx_django/locale'),
    )

    TEMPLATES = [{
        'DIRS': [os.path.join(BASE_DIR_PATH, "alexecx_django/templates")]
        },]